---

- name: Create namespace for Caktus Hosting Services
  k8s:
    context: "{{ k8s_context|mandatory }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_hosting_services_enabled | ternary('present', 'absent') }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ k8s_hosting_services_namespace }}"

- name: Create/update templates in Kubernetes
  k8s:
    context: "{{ k8s_context|mandatory }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_hosting_services_enabled | ternary('present', 'absent') }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition: "{{ lookup('template', 'hosting-services/backup-job.yaml.j2') }}"

- name: Include Papertrail tasks
  include_tasks: papertrail.yml

- name: Include New Relic tasks
  include_tasks: newrelic.yml
