- name: Create namespace for Papertrail
  k8s:
    context: "{{ k8s_context|mandatory }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_papertrail_logspout_enabled | ternary('present', 'absent') }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ k8s_papertrail_logspout_namespace }}"
  tags: [papertrail]

- name: Deploy Papertrail logspout
  k8s:
    context: "{{ k8s_context|mandatory }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_papertrail_logspout_enabled | ternary('present', 'absent') }}"
    wait: yes
    wait_timeout: "{{ k8s_wait_timeout }}"
    validate:
      fail_on_error: yes
      strict: yes
    # Stored locally to convert to template
    # https://help.papertrailapp.com/assets/files/papertrail-logspout-daemonset.yml
    definition: "{{ lookup('template', 'papertrail/papertrail-logspout-daemonset.yml.j2') }}"
  tags: [papertrail]
